// Copyright 2026 Steven Crothers
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cli

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/scrothers/pmmcp/internal/api"
	"github.com/scrothers/pmmcp/internal/ipc"
)

// This file holds the tool-call bridge and JSON-schema helpers used by the
// official MCP SDK server (mcp_sdk.go). The tools map to daemon IPC methods;
// there is no business logic here.

// genericInputSchema is used when a tool has no specialized schema.
var genericInputSchema = map[string]any{
	"type":       "object",
	"properties": map[string]any{},
}

// specializedSchemas holds richer inputSchema for well-known tools.
func specializedSchemas() map[string]map[string]any {
	return map[string]map[string]any{
		"pm_start": {
			"type": "object",
			"properties": map[string]any{
				"name":    map[string]any{"type": "string"},
				"command": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"cwd":     map[string]any{"type": "string"},
				"sandbox": map[string]any{"type": "string"},
			},
			"required": []string{"name", "command"},
		},
		"pm_run": {
			"type": "object",
			"properties": map[string]any{
				"name":        map[string]any{"type": "string", "description": "optional; autogenerated (run-…) when omitted"},
				"command":     map[string]any{"type": "array", "items": map[string]any{"type": "string"}, "description": "argv array — never a shell string"},
				"cwd":         map[string]any{"type": "string"},
				"sandbox":     map[string]any{"type": "string"},
				"wait":        map[string]any{"type": "boolean", "description": "block until the process exits"},
				"timeout_sec": map[string]any{"type": "integer"},
			},
			"required": []string{"command"},
		},
		"pm_stop":         idNameSchema(),
		"pm_restart":      idNameSchema(),
		"pm_remove":       idNameSchema(),
		"pm_status":       idNameSchema(),
		"pm_wait":         idNameSchema(),
		"pm_enable":       idNameSchema(),
		"pm_disable":      idNameSchema(),
		"pm_health_check": idNameSchema(),
		"pm_list": {
			"type": "object",
			"properties": map[string]any{
				"project": map[string]any{"type": "string"},
				"status":  map[string]any{"type": "string"},
			},
		},
		"pm_logs": {
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{"type": "string"}, "name": map[string]any{"type": "string"},
				"lines": map[string]any{"type": "integer"}, "stream": map[string]any{"type": "string"},
			},
		},
		"pm_grep": {
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{"type": "string"}, "name": map[string]any{"type": "string"},
				"pattern": map[string]any{"type": "string"},
			},
			"required": []string{"pattern"},
		},
		"pm_errors": idNameSchema(),
		"pm_events": {
			"type": "object",
			"properties": map[string]any{
				"process_id": map[string]any{"type": "string"},
				"limit":      map[string]any{"type": "integer"},
			},
		},
		"pm_events_subscribe": {
			"type": "object",
			"properties": map[string]any{
				"process_id": map[string]any{"type": "string", "description": "optional; scopes the preview to one process"},
			},
		},
		"pm_events_subscriptions": emptySchema(),
		"pm_events_unsubscribe": {
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{"type": "string"},
			},
			"required": []string{"id"},
		},
		"pm_group_create": {
			"type": "object",
			"properties": map[string]any{
				"id":         map[string]any{"type": "string", "description": "grp- id; auto-generated when omitted"},
				"name":       map[string]any{"type": "string"},
				"project_id": map[string]any{"type": "string"},
				"project":    map[string]any{"type": "string", "description": "alias for project_id"},
				"members": map[string]any{
					"type": "array",
					"items": map[string]any{
						"type": "object",
						"properties": map[string]any{
							"name":       map[string]any{"type": "string"},
							"process_id": map[string]any{"type": "string"},
							"depends_on": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
						},
						"required": []string{"name"},
					},
				},
			},
			"required": []string{"name"},
		},
		"pm_group_list": {
			"type": "object",
			"properties": map[string]any{
				"project_id": map[string]any{"type": "string"},
				"project":    map[string]any{"type": "string", "description": "alias for project_id"},
			},
		},
		"pm_group_remove": {
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{"type": "string"},
			},
			"required": []string{"id"},
		},
		"pm_group_restart": groupSelectorSchema(),
		"pm_group_start":   groupSelectorSchema(),
		"pm_group_status":  groupSelectorSchema(),
		"pm_group_stop":    groupSelectorSchema(),
		"pm_logs_export": {
			"type": "object",
			"properties": map[string]any{
				"id":      map[string]any{"type": "string"},
				"name":    map[string]any{"type": "string"},
				"project": map[string]any{"type": "string"},
			},
		},
		"pm_logs_ship": {
			"type": "object",
			"properties": map[string]any{
				"export_path": map[string]any{"type": "string", "description": "path from a prior pm_logs_export"},
				"sink_path":   map[string]any{"type": "string", "description": "destination path; must not already exist"},
				"path":        map[string]any{"type": "string", "description": "alias for sink_path"},
			},
			"required": []string{"export_path"},
		},
		"pm_logs_subscribe": {
			"type": "object",
			"properties": map[string]any{
				"process_id": map[string]any{"type": "string", "description": "optional; scopes the short preview follow to one process"},
			},
		},
		"pm_logs_unsubscribe": {
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{"type": "string"},
			},
			"required": []string{"id"},
		},
		"pm_metrics_snapshot": emptySchema(),
		"pm_profile_create": {
			"type": "object",
			"properties": map[string]any{
				"id":         map[string]any{"type": "string"},
				"name":       map[string]any{"type": "string", "description": "defaults to \"default\" when omitted"},
				"project_id": map[string]any{"type": "string", "description": "required (or project alias)"},
				"project":    map[string]any{"type": "string", "description": "alias for project_id"},
				"env":        map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "string"}},
			},
		},
		"pm_profile_delete": {
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{"type": "string"},
			},
			"required": []string{"id"},
		},
		"pm_profile_get": {
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{"type": "string"},
			},
			"required": []string{"id"},
		},
		"pm_profile_list": {
			"type": "object",
			"properties": map[string]any{
				"project_id": map[string]any{"type": "string"},
				"project":    map[string]any{"type": "string", "description": "alias for project_id"},
			},
		},
		"pm_profile_update": {
			"type": "object",
			"properties": map[string]any{
				"id":   map[string]any{"type": "string"},
				"name": map[string]any{"type": "string"},
				"env":  map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "string"}, "description": "replaces the full env map when provided"},
			},
			"required": []string{"id"},
		},
		"pm_profile_use": {
			"type": "object",
			"properties": map[string]any{
				"name":    map[string]any{"type": "string"},
				"session": map[string]any{"type": "string", "description": "defaults to the caller's session; a new session is opened if none exists"},
			},
		},
		"pm_session_end": {
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{"type": "string", "description": "session id to end; defaults to the caller's own session"},
			},
		},
		"pm_session_info": emptySchema(),
		"pm_share": {
			"type": "object",
			"properties": map[string]any{
				"target":     map[string]any{"type": "string", "description": "resource id being shared (e.g. a process id)"},
				"to_session": map[string]any{"type": "string"},
				"cap":        map[string]any{"type": "string", "description": "capability name to grant"},
			},
			"required": []string{"target", "to_session"},
		},
		"pm_unshare": {
			"type": "object",
			"properties": map[string]any{
				"target":     map[string]any{"type": "string"},
				"to_session": map[string]any{"type": "string"},
				"cap":        map[string]any{"type": "string", "description": "capability to revoke; omit to revoke all grants for the pair"},
			},
			"required": []string{"target", "to_session"},
		},
		"pm_apply": {
			"type": "object",
			"properties": map[string]any{
				"yaml": map[string]any{"type": "string", "description": "one of yaml, data, or path required"},
				"path": map[string]any{"type": "string"},
				"data": map[string]any{"type": "string"},
			},
		},
		"pm_audit_query": {
			"type": "object",
			"properties": map[string]any{
				"target": map[string]any{"type": "string"},
				"limit":  map[string]any{"type": "integer"},
			},
		},
		"pm_daemon_info":   emptySchema(),
		"pm_daemon_reload": emptySchema(),
		"pm_declare_show": {
			"type": "object",
			"properties": map[string]any{
				"yaml": map[string]any{"type": "string", "description": "one of yaml, data, or path required"},
				"path": map[string]any{"type": "string"},
				"data": map[string]any{"type": "string"},
			},
		},
		"pm_diff": {
			"type": "object",
			"properties": map[string]any{
				"yaml":          map[string]any{"type": "string", "description": "one of yaml, data, or path required"},
				"path":          map[string]any{"type": "string"},
				"data":          map[string]any{"type": "string"},
				"running_names": map[string]any{"type": "array", "items": map[string]any{"type": "string"}, "description": "override the live process set to diff against; defaults to actually-running names"},
			},
		},
		"pm_import": {
			"type": "object",
			"properties": map[string]any{
				"data":   map[string]any{"type": "string", "description": "one of data or path required"},
				"path":   map[string]any{"type": "string"},
				"format": map[string]any{"type": "string", "description": "only \"procfile\" (default) is supported"},
			},
		},
		"pm_ports": idNameSchema(),
		"pm_project_current": {
			"type": "object",
			"properties": map[string]any{
				"cwd": map[string]any{"type": "string", "description": "defaults to the daemon's own cwd when omitted"},
			},
		},
		"pm_project_list":     emptySchema(),
		"pm_runtime_info":     emptySchema(),
		"pm_sandbox_profiles": emptySchema(),
		"pm_secret_list":      emptySchema(),
		"pm_secret_ref_check": {
			"type": "object",
			"properties": map[string]any{
				"ref":  map[string]any{"type": "string", "description": "secret:// URI; one of ref or name required"},
				"name": map[string]any{"type": "string"},
				"path": map[string]any{"type": "string", "description": "optional project root for ref resolution"},
			},
		},
		"pm_secret_set": {
			"type": "object",
			"properties": map[string]any{
				"name":  map[string]any{"type": "string"},
				"path":  map[string]any{"type": "string", "description": "one of path or value required"},
				"value": map[string]any{"type": "string", "description": "SECURITY: stored in the keyring, but passed as a literal MCP tool argument — visible to the agent harness/logs unlike the CLI's stdin-only pmmcp secret set. Prefer a path ref; avoid value for real secrets."},
			},
			"required": []string{"name"},
		},
		"pm_update": {
			"type": "object",
			"properties": map[string]any{
				"id":      map[string]any{"type": "string"},
				"name":    map[string]any{"type": "string"},
				"project": map[string]any{"type": "string"},
				"command": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"cwd":     map[string]any{"type": "string"},
				"env":     map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "string"}},
				"restart": map[string]any{"type": "boolean", "description": "apply changes by restarting the process"},
			},
		},
		"pm_validate": {
			"type": "object",
			"properties": map[string]any{
				"yaml": map[string]any{"type": "string", "description": "one of yaml, data, or path required"},
				"path": map[string]any{"type": "string"},
				"data": map[string]any{"type": "string"},
			},
		},
		"pm_watch_set": {
			"type": "object",
			"properties": map[string]any{
				"id":      map[string]any{"type": "string"},
				"name":    map[string]any{"type": "string"},
				"project": map[string]any{"type": "string"},
				"path":    map[string]any{"type": "string"},
			},
			"required": []string{"path"},
		},
		"pm_watch_status": emptySchema(),
		"pm_webhook_create": {
			"type": "object",
			"properties": map[string]any{
				"id":     map[string]any{"type": "string", "description": "optional; auto-generated (wh-…) when omitted"},
				"url":    map[string]any{"type": "string"},
				"events": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
			},
			"required": []string{"url"},
		},
		"pm_webhook_delete": {
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{"type": "string"},
			},
			"required": []string{"id"},
		},
		"pm_webhook_list": emptySchema(),
		"pm_webhook_test": {
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{"type": "string"},
			},
			"required": []string{"id"},
		},
		"pm_webhook_update": {
			"type": "object",
			"properties": map[string]any{
				"id":     map[string]any{"type": "string"},
				"url":    map[string]any{"type": "string"},
				"events": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
			},
			"required": []string{"id"},
		},
		"pm_whoami": emptySchema(),
	}
}

func idNameSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"id": map[string]any{"type": "string"}, "name": map[string]any{"type": "string"},
		},
	}
}

// emptySchema is the explicit schema for tools that take no arguments — a
// deliberate declaration (additionalProperties: false), distinct from the
// generic fallback whose empty properties mean "unknown", not "none".
func emptySchema() map[string]any {
	return map[string]any{
		"type":                 "object",
		"properties":           map[string]any{},
		"additionalProperties": false,
	}
}

// groupSelectorSchema is the shared id-or-name group selector (with optional
// project scoping) used by the group lifecycle tools.
func groupSelectorSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"id":         map[string]any{"type": "string"},
			"name":       map[string]any{"type": "string"},
			"project_id": map[string]any{"type": "string"},
			"project":    map[string]any{"type": "string", "description": "alias for project_id"},
		},
	}
}

// schemaForTool returns the input schema for a tool, defaulting to the generic
// object schema when no specialized schema exists.
func schemaForTool(name string) map[string]any {
	if s, ok := specializedSchemas()[name]; ok {
		return s
	}
	return genericInputSchema
}

func mcpCall(ctx context.Context, endpoint, name string, args map[string]any) (string, error) {
	method, ok := ToolMethod[name]
	if !ok {
		return "", fmt.Errorf("unknown tool %s", name)
	}

	c, err := ipc.Dial(ctx, endpoint)
	if err != nil {
		// Dial already returns domain.Error with daemon_unavailable.
		return "", err
	}
	defer func() { _ = c.Close() }()

	// Optimized paths for tools with typed payloads / text-only results.
	switch name {
	case "pm_start":
		var pl api.StartPayload
		pl.Name, _ = args["name"].(string)
		if arr, ok := args["command"].([]any); ok {
			for _, a := range arr {
				pl.Command = append(pl.Command, fmt.Sprint(a))
			}
		}
		pl.Cwd, _ = args["cwd"].(string)
		pl.Sandbox, _ = args["sandbox"].(string)
		var out api.StartResult
		if err := c.Call(ctx, method, pl, &out); err != nil {
			return "", err
		}
		return prettyJSON(out)
	case "pm_run":
		var pl api.RunPayload
		pl.Name, _ = args["name"].(string)
		if arr, ok := args["command"].([]any); ok {
			for _, a := range arr {
				pl.Command = append(pl.Command, fmt.Sprint(a))
			}
		}
		pl.Cwd, _ = args["cwd"].(string)
		pl.Sandbox, _ = args["sandbox"].(string)
		pl.Wait, _ = args["wait"].(bool)
		if n, ok := args["timeout_sec"].(float64); ok {
			pl.TimeoutSec = int(n)
		}
		var out any
		if err := c.Call(ctx, method, pl, &out); err != nil {
			return "", err
		}
		return prettyJSON(out)
	case "pm_stop", "pm_restart", "pm_remove", "pm_status", "pm_wait", "pm_enable", "pm_disable", "pm_health_check":
		pl := api.IDPayload{}
		pl.ID, _ = args["id"].(string)
		pl.Name, _ = args["name"].(string)
		if n, ok := args["timeout_sec"].(float64); ok {
			pl.TimeoutSec = int(n)
		}
		var out any
		if err := c.Call(ctx, method, pl, &out); err != nil {
			return "", err
		}
		return prettyJSON(out)
	case "pm_list":
		pl := api.ListPayload{}
		pl.Project, _ = args["project"].(string)
		pl.Status, _ = args["status"].(string)
		var out []api.ProcessView
		if err := c.Call(ctx, method, pl, &out); err != nil {
			return "", err
		}
		return prettyJSON(out)
	case "pm_logs", "pm_grep", "pm_errors":
		pl := api.LogsPayload{}
		pl.ID, _ = args["id"].(string)
		pl.Name, _ = args["name"].(string)
		pl.Pattern, _ = args["pattern"].(string)
		pl.Stream, _ = args["stream"].(string)
		if n, ok := args["lines"].(float64); ok {
			pl.Lines = int(n)
		}
		var out api.LogsResult
		if err := c.Call(ctx, method, pl, &out); err != nil {
			return "", err
		}
		return out.Text, nil
	case "pm_daemon_info":
		var out api.DaemonInfoResult
		if err := c.Call(ctx, method, nil, &out); err != nil {
			return "", err
		}
		return prettyJSON(out)
	case "pm_whoami":
		var out api.WhoamiResult
		if err := c.Call(ctx, method, nil, &out); err != nil {
			return "", err
		}
		return prettyJSON(out)
	case "pm_events":
		pl := api.EventsPayload{}
		pl.ProcessID, _ = args["process_id"].(string)
		if n, ok := args["limit"].(float64); ok {
			pl.Limit = int(n)
		}
		var out []api.EventView
		if err := c.Call(ctx, method, pl, &out); err != nil {
			return "", err
		}
		return prettyJSON(out)
	}

	// Generic path: marshal arguments as JSON payload and Call the mapped method.
	var out any
	if err := c.Call(ctx, method, args, &out); err != nil {
		return "", err
	}
	if out == nil {
		return "{}", nil
	}
	return prettyJSON(out)
}

func prettyJSON(v any) (string, error) {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b), nil
}
