// Copyright 2026 Steven Crothers
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package webhook

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/url"
	"sort"
	"strings"
	"sync"
	"time"
)

// Sentinel errors.
var (
	// ErrNotFound is returned when a hook ID is unknown.
	ErrNotFound = errors.New("webhook: not found")
	// ErrInvalid is returned for invalid hook fields.
	ErrInvalid = errors.New("webhook: invalid")
	// ErrSSRF is returned when a delivery URL is blocked by policy (SSRF guard
	// or a destination that is not on the configured allowlist).
	ErrSSRF = errors.New("webhook: ssrf blocked")
)

// Hook is a registered outbound webhook destination.
type Hook struct {
	// ID is a unique registry key (caller-assigned or generated by higher layers).
	ID string
	// URL is the destination (http or https only).
	URL string
	// Events is an optional filter of event type names; empty means all.
	Events []string
	// Secret is the HMAC key. When set, deliveries carry an X-PMMCP-Signature
	// header (sha256=<hex> over the body). Higher layers resolve secret_ref into
	// this field; it is never serialized back out.
	Secret string
}

// Matches reports whether the hook should receive an event of the given type.
// An empty Events filter matches all event types.
func (h Hook) Matches(eventType string) bool {
	if len(h.Events) == 0 {
		return true
	}
	for _, e := range h.Events {
		if e == eventType {
			return true
		}
	}
	return false
}

// Registry is an in-memory hook store guarded by an allowlist admission policy.
type Registry struct {
	mu    sync.Mutex
	hooks map[string]Hook
	allow []string
}

// Option configures a Registry.
type Option func(*Registry)

// WithAllowlist sets the destination allowlist (host patterns or URL prefixes).
// Per, an empty allowlist means webhooks are disabled: every Create is
// rejected. Patterns are matched case-insensitively; "*.example.com" matches any
// subdomain (and the bare domain), a pattern containing "/" is a URL prefix,
// and any other pattern is an exact host.
func WithAllowlist(patterns ...string) Option {
	return func(r *Registry) {
		r.allow = append(r.allow, patterns...)
	}
}

// NewRegistry returns an empty Registry. Without WithAllowlist the allowlist is
// empty and every Create is rejected (webhooks disabled by default, ).
func NewRegistry(opts ...Option) *Registry {
	r := &Registry{hooks: make(map[string]Hook)}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// Create stores or replaces a hook by ID after admission checks.
func (r *Registry) Create(h Hook) error {
	if h.ID == "" {
		return fmt.Errorf("%w: empty id", ErrInvalid)
	}
	if err := admit(h.URL, r.allow); err != nil {
		return err
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	cp := h
	cp.Events = append([]string(nil), h.Events...)
	r.hooks[h.ID] = cp
	return nil
}

// List returns a copy of all hooks, sorted by ID for stable output.
func (r *Registry) List() []Hook {
	r.mu.Lock()
	defer r.mu.Unlock()
	out := make([]Hook, 0, len(r.hooks))
	for _, h := range r.hooks {
		cp := h
		cp.Events = append([]string(nil), h.Events...)
		out = append(out, cp)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

// Delete removes a hook by ID.
func (r *Registry) Delete(id string) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	if _, ok := r.hooks[id]; !ok {
		return fmt.Errorf("%w: %s", ErrNotFound, id)
	}
	delete(r.hooks, id)
	return nil
}

// Get returns a hook by ID.
func (r *Registry) Get(id string) (Hook, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	h, ok := r.hooks[id]
	if !ok {
		return Hook{}, fmt.Errorf("%w: %s", ErrNotFound, id)
	}
	h.Events = append([]string(nil), h.Events...)
	return h, nil
}

// admit enforces the allowlist then the SSRF policy for a destination URL.
func admit(raw string, allow []string) error {
	u, err := parseHTTPURL(raw)
	if err != nil {
		return err
	}
	if !allowlisted(raw, u, allow) {
		return fmt.Errorf("%w: %q not on allowlist", ErrSSRF, u.Hostname())
	}
	return validateHost(u)
}

// allowlisted reports whether raw/u matches any allowlist pattern. An empty
// allowlist matches nothing (disabled by default).
func allowlisted(raw string, u *url.URL, allow []string) bool {
	host := strings.ToLower(u.Hostname())
	lowRaw := strings.ToLower(raw)
	for _, p := range allow {
		p = strings.ToLower(strings.TrimSpace(p))
		switch {
		case p == "":
			continue
		case strings.Contains(p, "/"):
			if strings.HasPrefix(lowRaw, p) {
				return true
			}
		case strings.HasPrefix(p, "*."):
			if host == p[2:] || strings.HasSuffix(host, p[1:]) {
				return true
			}
		case host == p:
			return true
		}
	}
	return false
}

// ValidateURL enforces scheme and host SSRF policy without an allowlist. It is a
// best-effort registration/UX pre-check; the authoritative dial-time IP pin is
// enforced by Deliverer. Resolver errors are tolerated here (fail open) because
// delivery fails closed at dial.
func ValidateURL(raw string) error {
	return ValidateURLContext(context.Background(), raw)
}

// ValidateURLContext is ValidateURL using ctx (with a short timeout) for the DNS
// pre-check instead of a background context.
func ValidateURLContext(ctx context.Context, raw string) error {
	return validateURLContext(ctx, raw, net.DefaultResolver.LookupIPAddr)
}

// validateURLContext implements ValidateURLContext with an injectable resolver;
// test-only seam mirroring Deliverer.lookupIP.
func validateURLContext(ctx context.Context, raw string, lookupIPAddr func(ctx context.Context, host string) ([]net.IPAddr, error)) error {
	u, err := parseHTTPURL(raw)
	if err != nil {
		return err
	}
	if err := validateHost(u); err != nil {
		return err
	}
	if net.ParseIP(u.Hostname()) != nil {
		return nil // literal IP already checked in validateHost
	}
	lookupCtx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	ips, err := lookupIPAddr(lookupCtx, u.Hostname())
	if err != nil {
		return nil // unresolvable: allow register; delivery fails closed at dial
	}
	for _, ipa := range ips {
		if isBlockedIP(ipa.IP) {
			return fmt.Errorf("%w: resolved %s → %s", ErrSSRF, u.Hostname(), ipa.IP)
		}
	}
	return nil
}

// parseHTTPURL parses raw and enforces the http/https scheme and a non-empty host.
func parseHTTPURL(raw string) (*url.URL, error) {
	if raw == "" {
		return nil, fmt.Errorf("%w: empty url", ErrInvalid)
	}
	u, err := url.Parse(raw)
	if err != nil {
		return nil, fmt.Errorf("%w: parse: %w", ErrInvalid, err)
	}
	switch strings.ToLower(u.Scheme) {
	case "http", "https":
	default:
		return nil, fmt.Errorf("%w: scheme %q not allowed", ErrSSRF, u.Scheme)
	}
	if u.Hostname() == "" {
		return nil, fmt.Errorf("%w: empty host", ErrInvalid)
	}
	return u, nil
}

// validateHost blocks metadata hostnames and, for literal IPs, blocked ranges.
func validateHost(u *url.URL) error {
	host := u.Hostname()
	if isBlockedHostname(host) {
		return fmt.Errorf("%w: host %q", ErrSSRF, host)
	}
	if ip := net.ParseIP(host); ip != nil && isBlockedIP(ip) {
		return fmt.Errorf("%w: address %s", ErrSSRF, ip)
	}
	return nil
}

func isBlockedHostname(host string) bool {
	h := strings.ToLower(strings.TrimSpace(host))
	switch h {
	case "localhost", "localhost.localdomain", "metadata", "metadata.google.internal":
		return true
	}
	return strings.HasSuffix(h, ".localhost")
}

// isBlockedIP reports whether ip is unsafe for webhook egress.
// Blocks loopback, link-local (incl. 169.254.0.0/16 and metadata 169.254.169.254),
// and unspecified addresses. Does not block general RFC1918 private ranges
// (operators allowlist internal receivers explicitly via WithAllowlist).
func isBlockedIP(ip net.IP) bool {
	if ip == nil {
		return true
	}
	if ip.IsLoopback() || ip.IsLinkLocalUnicast() || ip.IsLinkLocalMulticast() || ip.IsUnspecified() {
		return true
	}
	// Belt-and-suspenders for the classic cloud metadata IPv4.
	if ip4 := ip.To4(); ip4 != nil && ip4.Equal(net.IPv4(169, 254, 169, 254)) {
		return true
	}
	return false
}
